# Разрешаем длинные строки, но сохраняем строгие правила вокруг структур
MD013: false  # Line length
MD022: true   # Blanks around headings
MD031: true   # Blanks around fenced code blocks
MD032: true   # Blanks around lists
MD058: true   # Blanks around tables

# --- SAFE REFACTOR ADDITIONS -------------------------------------------------
# Причины:
# - MD041: в репозитории встречаются Markdown-файлы, начинающиеся с front-matter (`---`).
#   Правило "первая строка - H1" конфликтует с front-matter и даёт ложные срабатывания.
#   Отключаем глобально, чтобы не править структуру всех документов.
MD041: false  # First line should be a top-level heading (disabled due to front-matter usage)

# - MD025: встречаются документы с несколькими H1 (намеренно, по структуре документа,
#   пример: workspace/wbs.md). Чтобы не переоформлять существующие материалы — отключаем.
MD025: false  # Single H1 in document (disabled to allow multiple top-level headings)

# --- NOTES -------------------------------------------------------------------
# Если позже потребуется точечно включить MD041/MD025:
# 1) Создайте .markdownlintignore для путей-исключений, а в этом файле верните правила в true.
# 2) Либо используйте отдельный конфиг для "строгого" набора правил в CI only job.

# --- LEGACY / HISTORY (для трассировки изменений; функционально не влияет) ---
# Ранее файл содержал только:
#   MD013: false
#   MD022: true
#   MD031: true
#   MD032: true
#   MD058: true
# После инцидентов с:
#   - MD041/first-line-heading в файлах с front-matter,
#   - MD025/single-title в документах с несколькими H1,
# были добавлены глобальные отключения, чтобы сохранить текущее форматирование и не ломать сборку.
