extends: default

ignore: |
  .github/workflows/ci.yml
  configs/workflows/app_build.yaml
  configs/agents.yaml

rules:
  line-length:
    max: 160
    level: warning
  braces:
    level: warning
  indentation:
    level: warning
  comments-indentation:
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']  # оставляем дефолт
